name: 운영 서버 배포

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Spring Boot application
        run: ./gradlew clean build --no-daemon -Pprofile=production

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.PRODUCTION_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PRODUCTION_AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload S3
        run: aws deploy push
          --application-name TaxiMate-production
          --ignore-hidden-files
          --s3-location s3://taxi-mate-production-bucket/archive/$GITHUB_SHA.zip
          --source .

      - name: Deploy EC2
        run: aws deploy create-deployment
          --application-name TaxiMate-production
          --deployment-config-name CodeDeployDefault.AllAtOnce
          --deployment-group-name TaxiMate-production-deployment-group
          --s3-location bucket=taxi-mate-production-bucket,key=archive/$GITHUB_SHA.zip,bundleType=zip
